# Generated by Django 2.2.3 on 2019-08-01 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrfProject',
            fields=[
                ('pid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pTitle', models.CharField(max_length=30)),
                ('pIntro', models.CharField(max_length=50, null=True)),
                ('pContext', models.TextField(null=True)),
                ('fin_time', models.DateField()),
                ('cre_time', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CrfProject')),
            ],
        ),
        migrations.DeleteModel(
            name='cfuser',
        ),
    ]
