# Generated by Django 2.2.3 on 2019-08-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crfproject',
            name='pImage',
            field=models.ImageField(blank=True, null=True, upload_to='cf/%Y%M%d', verbose_name='이미지'),
        ),
    ]
