# Generated by Django 2.2.3 on 2019-07-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrfProject',
            fields=[
                ('pType', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=10)),
                ('pTitle', models.CharField(max_length=30)),
                ('fin_time', models.DateField()),
                ('cre_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CrfUser',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='cfuser',
        ),
        migrations.AddField(
            model_name='crfproject',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to='crowdfunding.CrfUser'),
        ),
    ]
