# Generated by Django 2.2.3 on 2019-09-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crfuser',
            old_name='username',
            new_name='user_name',
        ),
    ]
