# Generated by Django 2.2.3 on 2019-09-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_auto_20190903_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crfproject',
            name='pImage',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='이미지'),
        ),
    ]
