# Generated by Django 2.2.3 on 2019-08-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_auto_20190801_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='crfproject',
            name='pType',
            field=models.CharField(choices=[('G', '게임'), ('A', '예술'), ('F', '패션'), ('C', '캠페인')], default='G', max_length=2),
        ),
    ]
