# Generated by Django 2.2.3 on 2019-08-22 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0003_auto_20190815_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='crfuser',
            name='usercoin',
            field=models.IntegerField(default=0, verbose_name='유저 코인'),
        ),
        migrations.AlterField(
            model_name='crfproject',
            name='pImage',
            field=models.ImageField(default='cf/default', null=True, upload_to='cf/%Y%M%d', verbose_name='이미지'),
        ),
        migrations.DeleteModel(
            name='ProjectUser',
        ),
        migrations.AddField(
            model_name='contribute',
            name='contrib_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='기여자'),
        ),
        migrations.AddField(
            model_name='contribute',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CrfProject', verbose_name='고유번호'),
        ),
    ]
