# Generated by Django 2.2.3 on 2019-07-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0004_projectuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='crfuser',
            name='img',
            field=models.ImageField(blank=True, upload_to='%email/img/profile'),
        ),
    ]
