# Generated by Django 2.2.3 on 2019-08-30 09:24

import crowdfunding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0005_auto_20190827_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crfproject',
            name='pImage',
            field=models.ImageField(default='static/default.jpg', upload_to=crowdfunding.models.user_path, verbose_name='이미지'),
        ),
    ]
